name: linotte
title: Langage Linotte
version: '3.11.0'
summary: Linotte est le langage de programmation entièrement en français.
description: |
  Inspiré des langages Basic, Logo et Java, Linotte permet d’assimiler rapidement les mécanismes et les logiques de la programmation car il ne requiert aucune notion mathématique ou technique.
    Linotte helps beginners in computer science to discover imperative and functional programming.
icon: snap/gui/linotte.png

base: core18
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
apps:
  linotte:
    extensions:
      - gnome-3-28
    command: $SNAP/jdk/bin/java -jar $SNAP/linotte-lanceur/Atelier.jar
    plugs: [ home, network , desktop, desktop-legacy , unity7 ]
parts:
  jdk:
    plugin: dump
    source: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz
    organize:
      '*': jdk/
  linotte:
    plugin: maven
    source: https://github.com/cpc6128/LangageLinotte.git
    source-tag: v3.11
    source-type: git
    maven-options:
      [ -DskipTests=true ]
    maven-targets:
      - linotte-lanceur
  exemples:
    plugin: dump
    after: [ linotte ]
    source-type: local
    source: /root/parts/linotte/build/linotte-dist/target
    organize:
      exemples: linotte-lanceur/exemples
