name: linotte
title: Langage Linotte
version: '3.14.0'
summary: Linotte est le langage de programmation entièrement en français.
description: |
  Inspiré des langages Basic, Logo et Java, Linotte permet d’assimiler rapidement les mécanismes et les logiques de la programmation car il ne requiert aucune notion mathématique ou technique.
    Linotte helps beginners in computer science to discover imperative and functional programming.
icon: snap/gui/linotte.png

base: core18
grade: stable
confinement: strict

apps:
  linotte:
    extensions:
      - gnome-3-28
    command: usr/lib/jvm/java-17-openjdk-amd64/bin/java -jar $SNAP/linotte-lanceur/Atelier.jar
    plugs: [ home, network , desktop, desktop-legacy , x11, audio-playback, browser-support ]
    environment:
      _JAVA_OPTIONS: -Duser.home=$SNAP_USER_DATA
parts:
  linotte:
    plugin: maven
    source: https://github.com/cpc6128/LangageLinotte.git
    source-tag: v3.14
    source-type: git
    maven-options:
      [ -DskipTests=true ]
    maven-targets:
      - linotte-lanceur
    stage-packages:
      - openjdk-17-jre
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
  exemples:
    plugin: dump
    after: [ linotte ]
    source-type: local
    source: /root/parts/linotte/build/linotte-dist/target
    organize:
      exemples: linotte-lanceur/exemples
