package org.linotte.frame.cahier.timbre.entite.e;

public enum ZoneActive {

	TIMBRE, PARAMETRE_1, PARAMETRE_2, PARAMETRES_FONCTION, CONDITION_SUIVANT, CONDITION_SUIVANT_SECONDAIRE, POUR_ACTEUR, POUR_INDEX_DEBUT, POUR_INDEX_FIN, DELEGUEE, CONDITION_FORMULE

}
